name: deploy-applications
permissions: {}
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: environment
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  AWS_REGION: ap-northeast-1

jobs:
  prepare:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      image-tag: ${{ steps.image-tag.outputs.tag }}
    steps:
      - name: Generate Image Tag
        id: image-tag
        run: |
          TAG=$(date +'%Y%m%d-%H%M%S')-${GITHUB_SHA::7}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: [prepare]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      ecr-registry-url: ${{ steps.set-ecr-url.outputs.url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/${{ vars.PROJECT_NAME }}-${{ inputs.environment }}-github-actions-role
          role-session-name: gh-oidc-${{ github.run_id }}-${{ github.run_attempt }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        run: |
          IMAGE_TAG="${{ needs.prepare.outputs.image-tag }}"
          ECR_URL="${{ steps.login-ecr.outputs.registry }}/${{ vars.PROJECT_NAME }}-${{ inputs.environment }}"
          docker build \
            -t $ECR_URL:$IMAGE_TAG \
            -t $ECR_URL:latest \
            -f environments/Dockerfile.deploy .
          docker push $ECR_URL:$IMAGE_TAG
          docker push $ECR_URL:latest

      - name: Set ECR Repository URL
        id: set-ecr-url
        run: |
          ECR_URL="${{ steps.login-ecr.outputs.registry }}/${{ vars.PROJECT_NAME }}-${{ inputs.environment }}"
          echo "Repository URL: $ECR_URL"
          echo "url=${ECR_URL}" >> $GITHUB_OUTPUT


  deploy:
    needs: [prepare, build-and-push]
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      image-tag: ${{ needs.prepare.outputs.image-tag }}
      environment: ${{ inputs.environment }}
      ecr-registry-url: ${{ needs.build-and-push.outputs.ecr-registry-url }}
    secrets:
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
    permissions:
      id-token: write
      contents: read