name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: environment
      stage:
        description: 'Deployment stage'
        type: choice
        options:
          - ecr-only
          - complete
        default: 'complete'
        required: true


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: print log
        run: echo "Hello, world!"