name: dev-${PROJECT_NAME_ENV}
services:
  backend:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - PROJECT_NAME=${PROJECT_NAME_ENV}-backend
      context: ../../
      dockerfile: environments/Dockerfile.backend
    env_file:
      - ../backend.env
    tty: true
    init: true
    volumes:
        - ../../applications/backend:/home/trailblazer/${PROJECT_NAME_ENV}-backend
    ports:
        - 8000:8000

  chrome-extension:
    build:
      args:
          - PROJECT_NAME=${PROJECT_NAME_ENV}-chrome-extension
      context: ../../
      dockerfile: environments/Dockerfile.chrome
    user: "node"
    tty: true
    init: true
    volumes:
        - ../../applications/chrome-extension:/home/node/${PROJECT_NAME_ENV}-chrome-extension
    ports:
        - 5173:5173

  terraform:
    build:
      args:
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
        - PROJECT_NAME=${PROJECT_NAME_ENV}-terraform
      context: ../../
      dockerfile: environments/Dockerfile.terraform
    env_file:
      - ../terraform.env
    tty: true
    entrypoint: bash
    volumes:
      - ../../terraform:/home/resq-terraform